config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get("/home", to: "welcome#home")
  get("/about", to: "welcome#about")
  get("/", { to: "welcome#home", as: :root })
  get("/admin/panel", to: "welcome#admin_panel")
  get("/dashboard", to: "welcome#dashboard")
  get("/users/:id/password/edit", { to: "users#edit_password", as: "edit_password" })
  patch("/users/:id/password/edit", { to: "users#update_password", as: "update_password" })
  post("quizzes/:id/answers", to: "questions#create_answer")
  get("/todo", to: "quiz_assignments#todo")

  resources :results
  resources :quiz_assignments
  resource :session, only: [:new, :create, :destroy]
  resources :departments
  resources :roles
  resources :quizzes do
    resources :questions do
      resources :options
    end
  end

  resources :users
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :find_quiz, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def new
    @quiz = Quiz.new
    @quiz.questions.build
  end

  def index
    @pagy, @quizzes = pagy(Quiz.all, items: 10)
  end

  def create
    @quiz = Quiz.new quiz_params
    @quiz.user = current_user #assigning the creator of the quiz
    @quiz.number_of_questions.times do #for each of the questions we will create an instance of a question with 4 options each
      q = Question.create()
      4.times do
        q.options << Option.new
      end
      @quiz.questions << q #we're assigning each question
    end

    if @quiz.save
      redirect_to quiz_questions_path(@quiz.id)
    else
      render :new
    end
  end

  def show
    @questions = @quiz.questions
    @question = @questions.first
    @options = @question.options.shuffle
    # we need to check if the current user has already taken this quiz
    @result = Result.find_by(quiz_id: @quiz.id, user_id: current_user.id)
  end

  def edit
    @question = Question.new
    @options = @question.options
  end

  def update
    #setting every unchecked option to false
    @quiz.questions.each { |question|
      question.options.each { |option|
        option.update(is_correct: false)
      }
    }
    if @quiz.update quiz_params
      redirect_to quiz_questions_path(@quiz.id), notice: "Quiz saved! "
    else
      render :edit
    end
  end

  def destroy
    @quiz.destroy
    redirect_to quizzes_path
  end

  private

  def find_quiz
    @quiz = Quiz.find params[:id]
  end

  def quiz_params
    params.require(:quiz).permit(:name, :number_of_questions, :correct_answers_to_pass, questions_attributes: [:id, :quiz_id, :name, :number_of_options, options_attributes: [:id, :question_id, :name, :is_correct]])
  end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
  def percentage_score
    @quiz = Quiz.find(params[:id])
    correct_answers = 0
    @quiz.questions.each do |question_id, option_id| # q_id means question_id and s_v means submitted_value
      question = Question.find(question_id)
      if question.op.answer_text == s_v.downcase.strip
        correct_answers += 1
      end
    end
    score = (correct_answers.to_f / number_of_questions.to_f * 100.0).round(2)
  end
end

app/views/quizzes/_form.html.erb
<div class="container">
  <%= render "shared/errors", obj: @quiz %>
  <div class="row justify-content-md-center">
    <div class="col-md-8 offset-md-1 m-auto">
      <div class="card">
        <div class="card-header card-header-success">
          <h4 class="card-title">Create a Quiz</h4>
        </div>
        <div class="card-body">
          <%= form_with(model: @quiz, local: true) do |form| %>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <%= form.label :name, class: "bmd-label-floating" %>
                  <%= form.text_field :name, class: "form-control" %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <%= form.label :number_of_questions, class: "bmd-label-floating" %>
                  <%= form.text_field :number_of_questions, rows: 10, class: "form-control" %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <%= form.label :correct_answers_to_pass, class: "bmd-label-floating" %>
                  <%= form.text_field :correct_answers_to_pass, rows: 10, class: "form-control" %>
                </div>
              </div>
            </div>
            <div>
            </div>
            <div class="form-group row justify-content-center">
              <%= form.submit class: "btn btn-success btn-lg" %>
            </div>
            <div class="form-group row justify-content-center">
              <div class="mb-3">
                <%= link_to "[ Cancel and return to home page ]", home_path, class: "text-info" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/quizzes/edit.html.erb
<h1 class="text-center mt-4">Edit Quiz</h1>
<div class="container">
  <%= render "shared/errors", obj: @quiz %>
  <div class="row justify-content-md-center">
    <div class="col-md-8 offset-md-1 m-auto">
      <div class="card">
        <div class="card-header card-header-success">
          <h4 class="card-title">Create a Quiz</h4>
        </div>
        <div class="card-body">
          <%= form_with(model: @quiz, local: true) do |form| %>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <%= form.label :name, class: "bmd-label-floating" %>
                  <%= form.text_field :name, class: "form-control" %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <%= form.label :number_of_questions, class: "bmd-label-floating" %>
                  <%= form.text_field :number_of_questions, rows: 10, class: "form-control" %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <%= form.label :correct_answers_to_pass, class: "bmd-label-floating" %>
                  <%= form.text_field :correct_answers_to_pass, rows: 10, class: "form-control" %>
                </div>
              </div>
            </div>
            <div>
            </div>
            <div class="form-group row justify-content-center">
              <%= form.submit class: "btn btn-success btn-lg" %>
            </div>
            <div class="form-group row justify-content-center">
              <div class="mb-3">
                <%= link_to "[ Cancel and return to home page ]", home_path, class: "text-info" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/quizzes/index.html.erb
<h1 class="text-center mt-4">Currently Available Quizzes</h1>
<div class="container">
  <div class="row justify-content-md-center">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
  <div class="row justify-content-md-center">
    <% @quizzes.each do |quiz| %>
      <div class="col-8 mt-4 offset-md-2">
        <div class="card">
          <div class="card-header card-header-success">
            <%= link_to(quiz.name, quiz_path(quiz.id), class: "text-white") %>
          </div>
          <div class="card-body">
            <p class='card-text'>
              created by:
              <%= quiz.user.full_name %>
            </p>
            <div class="form-group row justify-content-center">
              <%= link_to "Take the quiz", quiz_path(quiz.id), class: "btn btn-success mx-auto btn-lg" %>
              <%if current_user.is_admin?%>
                <%= link_to "Edit quiz", edit_quiz_path(quiz.id), class: "btn btn-warning mx-auto btn-lg" %>
                <%= link_to "Delete quiz", quiz_path(quiz.id), method: :delete, data: {confirm: "Deleting the quiz will also delete all the results and assignments for this quiz, are you sure?"},class: "btn btn-danger mx-auto btn-lg" %>
              <%end%>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/quizzes/new.html.erb
<h1 class="text-center mt-4">Create Quiz</h1>
<div class="container">
  <%= render "shared/errors", obj: @quiz %>
  <div class="row justify-content-md-center">
    <div class="col-md-6 offset-md-2 m-auto">
      <div class="card">
        <div class="card-header card-header-success">
          <h4 class="card-title">Create a Quiz</h4>
        </div>
        <div class="card-body">
          <%= form_with(model: @quiz, local: true) do |form| %>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <%= form.label :name, class: "bmd-label-floating" %>
                  <%= form.text_field :name, class: "form-control" %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <%= form.label :number_of_questions, class: "bmd-label-floating" %>
                  <%= form.text_field :number_of_questions, rows: 10, class: "form-control" %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <%= form.label :correct_answers_to_pass, class: "bmd-label-floating" %>
                  <%= form.text_field :correct_answers_to_pass, rows: 10, class: "form-control" %>
                </div>
              </div>
            </div>
            <div>
            </div>
            <div class="form-group row justify-content-center">
              <%= form.submit class: "btn btn-success btn-lg" %>
            </div>
            <div class="form-group row justify-content-center">
              <div class="mb-3">
                <%= link_to "[ Cancel and return to home page ]", home_path, class: "text-info" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/quizzes/show.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4 offset-md-2">
      <%if @result%>
        <div class="card">
          <div class="card-header card-header-success">
            Hey there <%= current_user.full_name %>
          </div>
          <div class="card-body">
            <p class="card-text">Hey there <%= current_user.full_name %>
              Looks like you have taken <%= @quiz.name %> quiz already. Would you like to view your result?
              <div class="form-group row justify-content-center">
                <%= link_to "Check Result",  result_path(@result), class: "btn btn-success btn-lg" %>
              </div>
            </div>
          <%else%>
            <div class="card">
              <div class="card-header card-header-success">
                Ready to take the quiz on <%= @quiz.name %> menu?
              </div>
              <div class="card-body">
                <p class="card-text">Hey there <%= current_user.full_name %>,
                  <%=@quiz.user.full_name%> created this quiz for you. There are <%= @quiz.number_of_questions %> questions in this quiz and you need to answer <%=@quiz.correct_answers_to_pass%> of them correctly to pass
                  <div class="form-group row justify-content-center">
                    <%= link_to "Let's Go!", quiz_question_path(@quiz.id, @quiz.questions.first.id), class: "btn btn-success btn-lg" %>
                  </div>
                </div>
              <%end%>            </div>
          </div>
        </div>
      </div>