config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get("/home", to: "welcome#home")
  get("/about", to: "welcome#about")
  get("/", { to: "welcome#home", as: :root })
  get("/admin/panel", to: "welcome#admin_panel")
  get("/dashboard", to: "welcome#dashboard")
  get("/users/:id/password/edit", { to: "users#edit_password", as: "edit_password" })
  patch("/users/:id/password/edit", { to: "users#update_password", as: "update_password" })
  post("quizzes/:id/answers", to: "questions#create_answer")
  get("/todo", to: "quiz_assignments#todo")

  resources :results
  resources :quiz_assignments
  resource :session, only: [:new, :create, :destroy]
  resources :departments
  resources :roles
  resources :quizzes do
    resources :questions do
      resources :options
    end
  end

  resources :users
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_secure_password
  validates :first_name, presence: true
  validates :last_name, presence: true
  belongs_to :role, optional: true
  has_many :quizzes
  has_many :results
  has_many :answered_questions
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }

  def full_name
    "#{first_name} #{last_name}".titleize
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_password, :update_password]
  before_action :require_same_user, only: [:edit, :update, :destroy, :edit_password, :update_password]

  def new
    @user = User.new
  end

  def index
    # @users = User.all
    @pagy, @users = pagy(User.all, items: 10)
  end

  def show
    @user = User.find params[:id]
    @roles = @user.role
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "#{@user.full_name} successfully signed up!"
    else
      render :new
    end
  end

  def edit_password
  end

  def update_password
    # first we check if the current password is correct
    if @user&.authenticate params[:user][:current_password]
      # then we take the new password and compare it with confirmation and current password
      new_password = params[:user][:new_password]
      new_password_confirmation = params[:user][:new_password_confirmation]
      new_password_valid = new_password != params[:user][:current_password]
      password_confirmed = new_password == new_password_confirmation
      #  if everything is correct we update the passord
      if new_password_valid && password_confirmed
        if @user.update password: new_password, password_confirmation: new_password_confirmation
          flash[:notice] = "Password updated successfully"
          redirect_to root_path
        else
          render :edit_password
        end
      else
        flash[:alert] = "Passwords do not match"
        render :edit_password
      end
    else
      flash[:alert] = "Inccorrect Password entered"
      render :edit_password
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated"
      redirect_to @user
    else
      render "edit"
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :role_id)
  end

  def require_same_user
    if current_user != @user && !current_user.is_admin?
      flash[:alert] = "You can only edit or delete your own account"
      redirect_to root_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="content">
  <%= render "shared/errors", obj: @user %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6 offset-md-3 m-auto">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title">Your Information</h4>
          </div>
          <div class="card-body">
            <%= form_with(model: @user, local: true) do |f| %>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <%= f.label :first_name, class: "bmd-label-floating" %>
                    <%= f.text_field :first_name, class: "form-control", placeholder: "Enter your first name", :required => true %>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <%= f.label :last_name, class: "bmd-label-floating" %>
                    <%= f.text_field :last_name, class: "form-control", placeholder: "Enter your last name", :required => true %>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-7">
                  <div class="form-group">
                    <%= f.label :email, class: "bmd-label-floating" %>
                    <%= f.email_field :email, class: "form-control", placeholder: "Enter your email address", :required => true %>
                  </div>
                </div>
                <%= f.collection_select :role_id, Role.all.order(name: :asc), :id, :name, { :prompt => true }, { class: "btn mx-auto btn-outline-light" } %>
              </div>
              <div class="form-group row justify-content-center">
                <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-primary btn-lg") %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="content">
  <%= render "shared/errors", obj: @user %>
  <div class="container">
    <div class="col-12 mt-4 offset-md-1">
      <h1 class="text-center mt-4">You can update your profile here</h1>
      <div class="col-md-10 m-auto">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title">Your Profile</h4>
          </div>
          <div class="card-body">
            <%= form_with(model: @user, local: true) do |f| %>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <%= f.label :first_name, class: "bmd-label-floating" %>
                    <%= f.text_field :first_name, class: "form-control", placeholder: "Enter your first name", :required => true %>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <%= f.label :last_name, class: "bmd-label-floating" %>
                    <%= f.text_field :last_name, class: "form-control", placeholder: "Enter your last name", :required => true %>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-7">
                  <div class="form-group">
                    <%= f.label :email, class: "bmd-label-floating" %>
                    <%= f.email_field :email, class: "form-control", placeholder: "Enter your email address", :required => true %>
                  </div>
                </div>
                <%= f.collection_select :role_id, Role.all.order(name: :asc), :id, :name, { :prompt => true }, { class: "btn mx-auto btn-outline-light" } %>
              </div>
              <div class="form-group row justify-content-center">
                <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-primary btn-lg") %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit_password.html.erb
<div class="content">
  <div class="container">
    <div class="col-12 mt-4 offset-md-1">  <%= render "shared/errors", obj: @user %>
      <h1 class="text-center mt-4">Change your password here</h1>
      <div class="col-md-10 m-auto">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title">New password must be different from the previous password
              <h4>
              </div>
              <div class="card-body">
                <%= form_with(model: @user, url: update_password_path(@user), local: true) do |f| %>
                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group">
                        <%= f.label :current_password, class: "bmd-label-floating" %>
                        <%= f.password_field :current_password, class: "form-control", placeholder: "Enter your current password", :required => true %>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group">
                        <%= f.label :new_password, class: "bmd-label-floating" %>
                        <%= f.password_field :new_password, class: "form-control", placeholder: "Create a password", :required => true %>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group">
                        <%= f.label :new_password_confirmation, class: "bmd-label-floating" %>
                        <%= f.password_field :new_password_confirmation, class: "form-control", placeholder: "Confirm your password", :required => true %>
                      </div>
                    </div>
                  </div>
                  <div class="form-group row justify-content-center">
                    <%= f.submit "Update", class: "btn btn-primary btn-lg" %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

app/views/users/index.html.erb
<h1 class="text-center mt-4">KTP Users</h1>
<div class="container">
  <div class="row justify-content-md-center">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
  <div class="row justify-content-md-center">
    <% @users.each do |user| %>
      <div class="col-8 mt-4 offset-md-2">
        <div class="card">
          <div class="card-header card-header-primary">
            <%= link_to user.full_name, user, class: "text-light" %>
          </div>
          <div class="card-body">
            <p class="card-text">works as <%= user.role&.name || "Role no longer exists" %></p>
            <p class="card-text">in the <%= user.role&.department&.name || "Department no longer exists" %> department </p>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for Know Thy Product</h1>
<div class="content">
  <%= render "shared/errors", obj: @user %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8 m-auto">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title">Enter Your Information</h4>
          </div>
          <div class="card-body">
            <%= form_with(model: @user, local: true) do |f| %>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <%= f.label :first_name, class: "bmd-label-floating" %>
                    <%= f.text_field :first_name, class: "form-control", placeholder: "Enter your first name", :required => true %>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <%= f.label :last_name, class: "bmd-label-floating" %>
                    <%= f.text_field :last_name, class: "form-control", placeholder: "Enter your last name", :required => true %>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <%= f.label :email, class: "bmd-label-floating" %>
                    <%= f.email_field :email, class: "form-control", placeholder: "Enter your email address", :required => true %>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <%= f.label :password, class: "bmd-label-floating" %>
                    <%= f.password_field :password, class: "form-control", placeholder: "Create a password", :required => true %>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <%= f.label :password_confirmation, class: "bmd-label-floating" %>
                    <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm your password", :required => true %>
                  </div>
                </div>
              </div>
              <div class="form-group row justify-content-center">
                <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-primary btn-lg") %>
              </div>
            <% end %>
          </div>
          <div class="form-group row justify-content-center">
            <div class="mb-3">
              <%= link_to "[ Cancel and return to home page ]", home_path, class: "text-info" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1 class="text-center mt-4">Profile of <%= @user.full_name %></h1>
<%= render "form" %>