config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get("/home", to: "welcome#home")
  get("/about", to: "welcome#about")
  get("/", { to: "welcome#home", as: :root })
  get("/admin/panel", to: "welcome#admin_panel")
  get("/dashboard", to: "welcome#dashboard")
  get("/users/:id/password/edit", { to: "users#edit_password", as: "edit_password" })
  patch("/users/:id/password/edit", { to: "users#update_password", as: "update_password" })
  post("quizzes/:id/answers", to: "questions#create_answer")
  get("/todo", to: "quiz_assignments#todo")

  resources :results
  resources :quiz_assignments
  resource :session, only: [:new, :create, :destroy]
  resources :departments
  resources :roles
  resources :quizzes do
    resources :questions do
      resources :options
    end
  end

  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.is_admin?
      can :manage, :all
    end

    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    alias_action(:create, :read, :update, :delete, to: :crud)
    alias_action(:create, :update, :delete, to: :cud)
    can(:cud, Quiz) do |quiz|
      user == quiz.user
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :result, optional: true
  belongs_to :option
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :users, through: :roles
  has_many :roles, dependent: :nullify
  validates :name, presence: true, uniqueness: true
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :question, optional: true
  has_one :answer, dependent: :destroy
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :quiz
  has_many :options, dependent: :destroy
  accepts_nested_attributes_for :options, allow_destroy: true
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :user
  has_many :questions, dependent: :destroy
  accepts_nested_attributes_for :questions,
                                allow_destroy: true,
                                reject_if: proc { |att| att["name"].blank? }

  has_many :options, through: :questions
  has_many :results, dependent: :destroy
  has_many :quiz_assignments, dependent: :destroy
  validates :number_of_questions, numericality: { only_integer: true }
  validates :correct_answers_to_pass, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: ->(quiz) { quiz.number_of_questions }, message: "must be between 0 & total number of questions" }
end

app/models/quiz_assignment.rb
class QuizAssignment < ApplicationRecord
  belongs_to :quiz
  belongs_to :role
  has_many :users, through: :roles
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :quiz
  belongs_to :user
  has_many :answers
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :department
  has_many :quiz_assignments, dependent: :nullify
  has_many :users, dependent: :nullify
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_secure_password
  validates :first_name, presence: true
  validates :last_name, presence: true
  belongs_to :role, optional: true
  has_many :quizzes
  has_many :results
  has_many :answered_questions
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }

  def full_name
    "#{first_name} #{last_name}".titleize
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_role, only: [:show, :edit, :update, :destroy]

  def new
    @role = Role.new
  end

  def index
    @pagy, @roles = pagy(Role.all, items: 10)
  end

  def create
    @role = Role.new role_params
    if @role.save
      redirect_to roles_path, notice: "New role created!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @role.update role_params
      redirect_to role_path(@role.id)
    else
      render :edit
    end
  end

  def show
    @users = @role.users.order(created_at: :desc)
  end

  def destroy
    @role.destroy
    redirect_to roles_path
  end

  private

  def find_role
    @role = Role.find params[:id]
  end

  def role_params
    params.require(:role).permit(:name, :department_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  # This method creates a link with `data-id` `data-fields` attributes. These attributes are used to create new instances of the nested fields through Javascript.
  def link_to_add_fields(name, f, association)

    # Takes an object (@person) and creates a new instance of its associated model (:addresses)
    # To better understand, run the following in your terminal:
    # rails c --sandbox
    # @person = Person.new
    # new_object = @person.send(:addresses).klass.new
    new_object = f.object.send(association).klass.new

    # Saves the unique ID of the object into a variable.
    # This is needed to ensure the key of the associated array is unique. This is makes parsing the content in the `data-fields` attribute easier through Javascript.
    # We could use another method to achive this.
    id = new_object.object_id

    # https://api.rubyonrails.org/ fields_for(record_name, record_object = nil, fields_options = {}, &block)
    # record_name = :addresses
    # record_object = new_object
    # fields_options = { child_index: id }
    # child_index` is used to ensure the key of the associated array is unique, and that it matched the value in the `data-id` attribute.
    # `person[addresses_attributes][child_index_value][_destroy]`
    fields = f.fields_for(association, new_object, child_index: id) do |builder|

      # `association.to_s.singularize + "_fields"` ends up evaluating to `address_fields`
      # The render function will then look for `views/people/_address_fields.html.erb`
      # The render function also needs to be passed the value of 'builder', because `views/people/_address_fields.html.erb` needs this to render the form tags.
      render(association.to_s.singularize + "_fields", f: builder)
    end

    # This renders a simple link, but passes information into `data` attributes.
    # This info can be named anything we want, but in this case we chose `data-id:` and `data-fields:`.
    # The `id:` is from `new_object.object_id`.
    # The `fields:` are rendered from the `fields` blocks.
    # We use `gsub("\n", "")` to remove anywhite space from the rendered partial.
    # The `id:` value needs to match the value used in `child_index: id`.
    link_to(name, "#", class: "add_fields", data: { id: id, fields: fields.gsub("\n", "") })
  end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
  def percentage_score
    @quiz = Quiz.find(params[:id])
    correct_answers = 0
    @quiz.questions.each do |question_id, option_id| # q_id means question_id and s_v means submitted_value
      question = Question.find(question_id)
      if question.op.answer_text == s_v.downcase.strip
        correct_answers += 1
      end
    end
    score = (correct_answers.to_f / number_of_questions.to_f * 100.0).round(2)
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/roles/_form.html.erb
<div class="container">
  <%= render "shared/errors", obj: @role %>
  <div class="row justify-content-md-center">
    <div class="col-md-6 offset-md-2 m-auto">
      <div class="card">
        <div class="card-header card-header-warning">
          <h4 class="card-title">New Role</h4>
        </div>
        <div class="card-body">
          <%= form_with(model: @role, local: true) do |form| %>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group row justify-content-center">
                  <%= form.label :name, class: "bmd-label-floating" %>
                  <%= form.text_field :name, class: "form-control" %>
                </div>
              </div>
            </div>
            <div class="col-md-12">
              <div class="form-group row justify-content-center">
                <%= form.label :department, class: "bmd-label-floating" %>
              </div>
            </div>
            <div class="form-group row justify-content-center">
              <%= form.collection_select :department_id, Department.all.order(name: :asc), :id, :name, { :prompt => true }, { class: "btn btn-outline-light" } %>
            </div>
          </div>
          <div class="form-group row justify-content-center">
            <%= form.submit(@role.new_record? ? "Create" : "Update", class: "btn btn-warning btn-lg") %>
          </div>
          <div class="form-group row justify-content-center">
            <div class="mb-3">
              <%= link_to "[ Cancel and return to home page ]", home_path, class: "text-info" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/roles/edit.html.erb
<h1 class="text-center mt-4">Create new role</h1>
<div class="container">
  <%= render "shared/errors", obj: @role %>
  <div class="row justify-content-md-center">
    <div class="col-md-8 offset-md-1 m-auto">
      <div class="card">
        <div class="card-header card-header-warning">
          <h4 class="card-title">New Role</h4>
        </div>
        <div class="card-body">
          <%= form_with(model: @role, local: true) do |form| %>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group row justify-content-center">
                  <%= form.label :name, class: "bmd-label-floating" %>
                  <%= form.text_field :name, class: "form-control" %>
                </div>
              </div>
            </div>
            <div class="col-md-12">
              <div class="form-group row justify-content-center">
                <%= form.label :department, class: "bmd-label-floating" %>
              </div>
            </div>
            <div class="form-group row justify-content-center">
              <%= form.collection_select :department_id, Department.all.order(name: :asc), :id, :name, { :prompt => true }, { class: "btn btn-outline-light" } %>
            </div>
          </div>
          <div class="form-group row justify-content-center">
            <%= form.submit class: "btn btn-warning btn-lg" %>
          </div>
          <div class="form-group row justify-content-center">
            <div class="mb-3">
              <%= link_to "[ Cancel and return to home page ]", home_path, class: "text-info" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/roles/index.html.erb
<h1 class="text-center ml-4 mt-4">Currently available roles</h1>
<div class="container">
  <div class="row justify-content-md-center">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
  <div class="row justify-content-md-center">
    <% @roles.each do |role| %>
      <div class="col-8 mt-4 offset-md-2">
        <div class="card">
          <div class="card-header card-header-warning">
            <%= link_to(role.name, role_path(role), class: "text-white") %>
          </div>
          <div class="card-body">
            <%role.users.each do |user|%>
              <p class='card-text'>
                <%=user.full_name%>
              </p>
            <%end%>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/roles/new.html.erb
<h1 class="text-center mt-4">Create new role</h1>
<%= render "form" %>

app/views/roles/show.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4 offset-md-2">
      <div class="card">
        <div class="card-header card-header-warning text-white">
          <%= @role.name %>
        </div>
        <div class="card-body">
          <% @role.users.each do |user|%>
            <p class="card-text"><%=user.full_name %>
            </p>
          <%end%>
          <div class="form-group row justify-content-center">
            <%if current_user.is_admin?%>
              <%= link_to "Edit Role", edit_role_path(@role.id), class: "btn btn-warning mx-auto btn-lg" %>
              <%= link_to "Delete Role", role_path(@role.id), method: :delete, data: {confirm: "Are you sure?"},class: "btn btn-danger mx-auto btn-lg" %>
            <%end%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>