config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get("/home", to: "welcome#home")
  get("/about", to: "welcome#about")
  get("/", { to: "welcome#home", as: :root })
  get("/admin/panel", to: "welcome#admin_panel")
  get("/dashboard", to: "welcome#dashboard")
  get("/users/:id/password/edit", { to: "users#edit_password", as: "edit_password" })
  patch("/users/:id/password/edit", { to: "users#update_password", as: "update_password" })
  post("quizzes/:id/answers", to: "questions#create_answer")
  get("/todo", to: "quiz_assignments#todo")

  resources :results
  resources :quiz_assignments
  resource :session, only: [:new, :create, :destroy]
  resources :departments
  resources :roles
  resources :quizzes do
    resources :questions do
      resources :options
    end
  end

  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.is_admin?
      can :manage, :all
    end

    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    alias_action(:create, :read, :update, :delete, to: :crud)
    alias_action(:create, :update, :delete, to: :cud)
    can(:cud, Quiz) do |quiz|
      user == quiz.user
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :result, optional: true
  belongs_to :option
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :users, through: :roles
  has_many :roles, dependent: :nullify
  validates :name, presence: true, uniqueness: true
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :question, optional: true
  has_one :answer, dependent: :destroy
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :quiz
  has_many :options, dependent: :destroy
  accepts_nested_attributes_for :options, allow_destroy: true
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :user
  has_many :questions, dependent: :destroy
  accepts_nested_attributes_for :questions,
                                allow_destroy: true,
                                reject_if: proc { |att| att["name"].blank? }

  has_many :options, through: :questions
  has_many :results, dependent: :destroy
  has_many :quiz_assignments, dependent: :destroy
  validates :number_of_questions, numericality: { only_integer: true }
  validates :correct_answers_to_pass, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: ->(quiz) { quiz.number_of_questions }, message: "must be between 0 & total number of questions" }
end

app/models/quiz_assignment.rb
class QuizAssignment < ApplicationRecord
  belongs_to :quiz
  belongs_to :role
  has_many :users, through: :roles
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :quiz
  belongs_to :user
  has_many :answers
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :department
  has_many :quiz_assignments, dependent: :nullify
  has_many :users, dependent: :nullify
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_secure_password
  validates :first_name, presence: true
  validates :last_name, presence: true
  belongs_to :role, optional: true
  has_many :quizzes
  has_many :results
  has_many :answered_questions
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }

  def full_name
    "#{first_name} #{last_name}".titleize
  end
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
  def percentage_score
    @quiz = Quiz.find(params[:id])
    correct_answers = 0
    @quiz.questions.each do |question_id, option_id| # q_id means question_id and s_v means submitted_value
      question = Question.find(question_id)
      if question.op.answer_text == s_v.downcase.strip
        correct_answers += 1
      end
    end
    score = (correct_answers.to_f / number_of_questions.to_f * 100.0).round(2)
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small class= "text-white">Stas Anikin &copy; 2021</small>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header id="sticky-header" class="py-1 bg-dark text-white">
  <div class="container justify-content-center" id="header">
    <%= link_to "Know Thy Product", root_path, class: "h2", id: 'header-name' %>
  </div>
</header>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div>

app/views/layouts/_navbar.html copy.erb
<nav class="navbar navbar-expand-lg mx-auto navbar-light  nav-fill w-100 bg-light">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <li class="nav-item active">
      <%= link_to "Home", root_path, class: "nav-link-active text-dark" %>
    </li>
    <li class="nav-item active"><%= material_icon.face %>
      <%= link_to "Departments", departments_path, class: "nav-link-active text-dark" %>
    </li>
    <li class="nav-item active">
      <%= link_to "Quizzes", quizzes_path, class: "nav-link-active text-dark" %>
    </li>
    <li class="nav-item active">
      <%= link_to "Results", results_path, class: "nav-link-active text-dark" %>
    </li>
    <li class="nav-item active">
      <%= link_to "Create a Quiz", new_quiz_path, class: "nav-link-active text-dark" %>
    </li>
    <li class="nav-item active">
      <%= link_to "Users", users_path, class: "nav-link-active text-dark" %>
    </li>
    <li class="nav-item active">
      <%= link_to "About", about_path, class: "nav-link-active text-dark" %>
    </li>
    <% if user_signed_in? %>
      <li class="nav-item active text-dark">
        <span>Hello, <%= current_user.full_name %></span>
      </li>
      <li class="nav-item">
        <%= link_to "Logout", session_path, method: :delete,
                                    data: { confirm: "Are you sure you want to log out?" }, class: "nav-link-active text-dark" %>
      </li>
    <% else %>
      <li class="nav-item active">
        <%= link_to "Login", new_session_path, class: "nav-link-active text-dark" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Sign Up", new_user_path, class: "nav-link-active text-dark" %>
      </li>
    <% end %>
  </div>
</nav>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute navbar-fixed-top mt-0" id='navbar'>
  <div class="container-fluid">
    <div class="navbar-wrapper">
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
      <span class="sr-only">Toggle navigation</span>
      <span class="navbar-toggler-icon icon-bar"></span>
      <span class="navbar-toggler-icon icon-bar"></span>
      <span class="navbar-toggler-icon icon-bar"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end">
      <%if user_signed_in?%>
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <a class="nav-link" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="material-icons">notifications</i>
              <%if @unfinished_quizzes&&@unfinished_quizzes.length>0%>
                <span class="notification"><%=@unfinished_quizzes.length%></span>
                <div class="ripple-container"></div>
              <%end%>
            </a>              <%if @unfinished_quizzes&&@unfinished_quizzes.length>0%>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="/todo">You have <%=@unfinished_quizzes.length%> outstanding quizzes</a>
              </div>
            <%else%>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="/todo">You have no outstanding quizzes</a>
              </div>
            <%end%>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link" href="javascript:;" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="material-icons">person</i>
              <p class="d-lg-none d-md-block">
                Account
              </p>
              <div class="ripple-container"></div>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
              <a class="dropdown-item" href="/users/<%=current_user.id%>/edit">Update Profile</a>
              <a class="dropdown-item" href="/users/<%=current_user.id%>/password/edit">Change Password</a>
              <a class="dropdown-item" href="/todo">My Assignments</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="/session" data-method="delete">Log out</a>
            </div>
          </li>
        </ul>
      <%end%>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<%if user_signed_in?%>
  <div class="sidebar" data-color="purple" data-background-color="white">
    <div class="logo">
      <a href="/home" class="simple-text logo-normal">
        Know Thy Product
      </a>
      <%= link_to(current_user.full_name, edit_user_path(current_user), class: "simple-text text-primary logo-normal") %>
    </div>
    <div class="sidebar-wrapper">
      <ul class="nav">
        <li class="nav-item dropdown">
          <a class="nav-link" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="material-icons">dashboard</i>
            <p>Departments</p>
            <div class="ripple-container"></div>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="/departments">  <i class="material-icons">dashboard</i>
              <p>Departments Index</p>
            </a>
            <a class="dropdown-item" href="/departments/new">  <i class="material-icons">dashboard_customize</i>
              <p>Create Department</p>
            </a>
            <a class="dropdown-item" href="/roles">  <i class="material-icons">work</i>
              <p>Roles Index</p>
            </a>
            <a class="dropdown-item" href="/roles/new">  <i class="material-icons">create_new_folder</i>
              <p>Create Role</p>
            </a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="material-icons">quiz</i>
            <p>Quizzes</p>
            <div class="ripple-container"></div>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="/quizzes">  <i class="material-icons">quiz</i>
              <p>Quizzes Index</p>
            </a>
            <a class="dropdown-item" href="/quizzes/new">  <i class="material-icons">create</i>
              <p>Create Quiz</p>
            </a>
            <a class="dropdown-item" href="/quiz_assignments/new">  <i class="material-icons">assignment_return</i>
              <p>Assign Quiz</p>
            </a>
            <a class="dropdown-item" href="/quiz_assignments">  <i class="material-icons">assignment</i>
              <p>Current Assignments</p>
            </a>
            <a class="dropdown-item" href="/results">  <i class="material-icons">grading</i>
              <p>Results</p>
            </a>
          </div>
        </li>
        <li class="nav-item ">
          <a class="nav-link" href="/users">
            <i class="material-icons">people</i>
            <p>Users</p>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/session" data-method="delete">
            <i class="material-icons">logout</i>
            <p>Logout</p>
          </a>
        </li>
      </ul>
      <div id='sticky-footer'>
        <h5>Stas Anikin &copy; 2021</h5>
      </div>
    </div>
  </div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KnowThyProduct</title>
    <meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_pack_tag "application" %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" %>
    <%# <%= favicon_link_tag asset_path("logo.jpeg") %> %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" %>
  </head>
  <body>
    <%= render "layouts/sidebar" %>
    <%= render "layouts/navbar" unless @disable_navbar&&!user_signed_in? %>
    <div class="wrapper">
      <%= render "layouts/messages" %>
      <main class="flex-fill">
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>